config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :categories
  resources :questions

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  get 'tests' => 'tests#index'
  get 'tests/:category_id' => 'tests#start', as: 'tests_start'

  get 'ranking/index' => 'ranking#index', as: 'ranking_index'
  get 'ranking/show/:category_id' => 'ranking#show', as: 'ranking_show'

  get 'apis/next_question' => 'apis#next_question'
  post 'apis/finish_test' => 'apis#finish_test'
  get 'apis/category_auto_comp' => 'apis#category_auto_comp'
  
  get 'profiles/edit' => 'profiles#edit', as: 'profile_edit'
  post 'profiles/update' => 'profiles#update'

  namespace :apis do
    resources :answers
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  belongs_to :question_option

  def is_correct?
    correct_flg
  end
 
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_attached_file :image,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/

  has_many :questions

  validates :name, presence: true

  scope :name_like, -> text { where('name like ?', "%#{text}%") }

end

app/models/pack.rb
class Pack < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base

  scope :category_id_is, -> category_id { where(category_id: category_id) }
  
  belongs_to :category
  has_many :question_options
  has_many :answers

  accepts_nested_attributes_for :question_options

  validates :text, presence: true
  validates :category_id, presence: true,
    :uniqueness => {:scope => [:text]},
                    :if => Proc.new{|f| f.new_record?}
  validates :user_id, presence: true
  
end

app/models/question_option.rb
class QuestionOption < ActiveRecord::Base

  belongs_to :question
  has_many :answers


  def is_correct?
    correct_flg
  end
end

app/models/question_pack.rb
class QuestionPack < ActiveRecord::Base
end

app/models/question_rating.rb
class QuestionRating < ActiveRecord::Base
end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
end

app/models/reference.rb
class Reference < ActiveRecord::Base
end

app/models/test_ranking.rb
class TestRanking

  def self.setup(category_id)
    TestResult.category_id_is(category_id).each do |test_result|
      redis.zadd("ranking-#{category_id}", test_result.point, test_result.user_id)
    end
  end
 
  # 現在の順位
  def rank(test_result)
    Rankable.redis.zrevrank("ranking-#{category_id}", self.id) + 1
  end
 
  # 現在のスコア（この例だとユーザの保持するポイント）
  def score(category_id)
    Rankable.redis.zscore("ranking-#{category_id}", self.id)
  end
 
  # スコアの更新
  def update_score(category_id, user_id)
    Rankable.redis.zincrby('ranking', got_point, self.id)
  end
 
  private
 
  def self.redis
    @redis ||= Redis.new
  end

app/models/test_result.rb
class TestResult < ActiveRecord::Base

  include TestRanking

  belongs_to :user
  belongs_to :category

  scope :category_id_is, -> category_id { where(category_id: category_id) }

end

app/models/user.rb
require "open-uri"
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook, :github, :twitter]
 
  has_many :questions
  has_many :test_results

  has_attached_file :image,
    styles: { medium: "300x300>", thumb: "100x100>" },
    default_url: "/images/:style/missing.png"
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }  

  scope :uid_is, -> uid { where(uid: uid) }
  scope :is_facebook_user, -> { where(provider: "facebook") }
  scope :is_github_user, -> { where(provider: "github") }
  scope :provider_is, -> provider { where(provider: provider) }
   
  def set_image_from_auth(image_url)
    avatar_url = URI.parse(image_url)
    avatar_url.scheme = 'https'
    avatar_url.to_s
    self.image = open(avatar_url) # assuming the user model has an image
  end

  def took_tests_categories
    test_results.map(&:category).uniq
  end

  class << self
    def find_or_create_by_auth(omniauth_params)
      self.provider_is(omniauth_params.provider).uid_is(omniauth_params.uid).first_or_initialize.tap do |user|
        user.provider = omniauth_params.provider
        user.uid = omniauth_params.uid
        #emailは一旦設定されてなかったら空文字列追加
        user.email = omniauth_params.info.email.presence || "hoge#{Devise.friendly_token[0,3]}@qis.com"
        user.password = Devise.friendly_token[0,20]
        user.name = omniauth_params.info.name   # assuming the user model has a name
        user.access_token = omniauth_params.credentials.token 
        user.set_image_from_auth(omniauth_params.info.image) # assuming the user model has an image
        user.save!
      end
    end
  end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Qis"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    - @javascripts.each do |javascript|
      = javascript_include_tag javascript

  body
    .navbar.navbar-static-top
      .container
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"]
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to 'Qis', root_path, { class: 'navbar-brand' }
        .nav-collapse.navbar-responsive-collapse
          - if user_signed_in?
            ul.nav.navbar-nav
              li
                = link_to "問題を作る", new_question_path
              li
                = link_to "カテゴリーを作る", new_category_path
              li
                = link_to "テストを受ける", tests_path
              li
                = link_to "ランキングをみる", ranking_index_path
              li
                = link_to "プロフィールを編集する", profile_edit_path
          ul.nav.navbar-nav
            - unless user_signed_in?
              li
                = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
                = link_to "Sign in with Github", user_omniauth_authorize_path(:github)
                = link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter)
            - else
              li
                = image_tag current_user.image.url(:thumb)
              li
                = link_to("Sign out", destroy_user_session_path, method: :delete)
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      footer
        p
          | © Konya Company 2014

app/views/tests_cp/index.html.slim
- @categories.each do |category|
  = link_to tests_start_path(category_id: category.id) do
    = category.name
    = image_tag category.image.url(:thumb)